# bot_type
OPEN_AI = "openAI"
CHATGPT = "chatGPT"
BAIDU = "baidu"

IMAGE = "IMAGE"
IMAGE_RAW = "IMAGE_RAW"
IMAGE_SD = "IMAGE_SD"
IMAGE_INAPPROPRIATE = "IMAGE_INAPPROPRIATE"

TEXT = "TEXT"
TEXT_ONCE = "TEXT_ONCE"

TIMELINESS = "TIMELINESS"
TIMELINESS_INAPPROPRIATE = "TIMELINESS_INAPPROPRIATE"